apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-1-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-1-web
  template:
    metadata:
      labels:
        app: challenge-1-web
    spec:
      nodeSelector:
          worker: istrue
      containers:
        - name: challenge-1-web
          imagePullPolicy: Always
          image: viralnico/challenge:1
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: http
            - containerPort: 20
              name: ftp-data
            - containerPort: 21
              name: ftp-control
            - containerPort: 22
              name: ssh
            - containerPort: 443
              name: https
            - containerPort: 8080
              name: custom-port
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-1-web-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    metallb.universe.tf/allow-shared-ip: "challenge-1-web-192.168.0.222"
spec:
  selector:
    app: challenge-1-web
  type: LoadBalancer
  loadBalancerIP: 192.168.0.222
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 20
      name: ftp-data
      targetPort: 20
    - port: 21
      name: ftp-control
      targetPort: 21
    - port: 22
      name: ssh
      targetPort: 22
    - port: 443
      name: https
      targetPort: 443
    - port: 8080
      name: custom-port
      targetPort: 8080
