version: '3'
services:
  c1-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "85:80"
      - "20-21:20-21"
      - "2222:22"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./web:/var/www/html
      - ./notes:/home/worker/notes
