version: '3'
services:
  c1-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 85:80
      - 20-21:20-21
      - 22:22
      - 443:443
      - 3306:3306
      - 27017:27017
      - 6375:6379
      - 5432:5432
      - 9200:9200
      - 5601:5601
      - 8080:8080
    volumes:
      - ./web:/var/www/html
      - ./notes:/home/worker/notes
