apiVersion: v1
kind: Service
metadata:
  name: challenge-4-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    metallb.universe.tf/allow-shared-ip: "challenge-4-192.168.0.249"

spec:
  selector:
    app: challenge-4-web
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-4-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-4-web
  template:
    metadata:
      labels:
        app: challenge-4-web
    spec:
      containers:
        - name: challenge-4-web
          image: viralnico/challenge:4-web
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-4-ssh
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    metallb.universe.tf/allow-shared-ip: "challenge-4-192.168.0.250"
spec:
  selector:
    app: challenge-4-ssh
  ports:
    - protocol: TCP
      port: 222
      targetPort: 22
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-4-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-4-ssh
  template:
    metadata:
      labels:
        app: challenge-4-ssh
    spec:
      containers:
        - name: challenge-4-ssh
          image: viralnico/challenge:4-ssh
          imagePullPolicy: Always
          ports:
            - containerPort: 222
