version: '3'
services:
  c4-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    volumes:
      - ./web:/home/node/app
  c4-ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    ports:
      - "222:22"
    volumes:
      - ./ssh:/home/modchat/personal
