apiVersion: v1
kind: Service
metadata:
  name: challenge-checker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    metallb.universe.tf/allow-shared-ip: "challenge-checker-192.168.0.246"
spec:
  selector:
    app: challenge-checker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-checker
  template:
    metadata:
      labels:
        app: challenge-checker
    spec:
      containers:
        - name: challenge-checker
          image: viralnico/challenge:check
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
