version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    ports:
      - "8035:80"
    volumes:
      - ./web:/var/www/html
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    command:
      - --ssl=0
      - --ssl-cert=0
      - --ssl-key=0
      - --ssl-cipher=0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_DATABASE=workers
    volumes:
      - ./db-data:/var/lib/mysql
