version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    ports:
      - "8035:80"
    volumes:
      - ./web:/var/www/html
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_USER=admindb
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_DATABASE=workers
