apiVersion: v1
kind: Service
metadata:
  name: challenge-5-app
spec:
  selector:
    app: challenge-5-app
  ports:
    - protocol: TCP
      port: 6374
      targetPort: 6374
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-5-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-5-app
  template:
    metadata:
      labels:
        app: challenge-5-app
    spec:
      containers:
        - name: challenge-5-app
          image: viralnico/challenge:5
          imagePullPolicy: Always
          ports:
            - containerPort: 6374
